-- Dropping tables with foreign key constraints first
drop table if exists favorites;
drop table if exists tags;

-- Dropping tables without foreign keys
drop table if exists labels;
drop table if exists users;
drop table if exists celestial_bodies;

-- Creating tables without foreign keys
create table users(
  userid int(10) not null primary key auto_increment,
  username varchar(100) not null unique,
  hash varchar(60) not null,
  -- Speed up research on username
  index (username)
);

create table celestial_bodies(
  id int(10) not null primary key auto_increment,
  name varchar(100) not null unique,
  type varchar(13) not null,
  -- Speed up research on star name
  index (name)
);

create table labels(
  label_id int(10) not null primary key auto_increment,
  name varchar(100) not null unique,
  -- Speed up research on the tag's content
  index(name)
);

-- A tag is a label, a user and a celestial_body
create table tags(
  tag_id int(10) not null primary key auto_increment,
  celestial_bodies_id int(10) not null,
  label_id int(10) not null,
  userid int(10) not null,
  foreign key (celestial_bodies_id) references celestial_bodies(id),
  foreign key (label_id) references labels(label_id),
  foreign key (userid) references users(userid),
  -- A tuple (tag_id, celestial_bodies_id, label_id) must exist only once
  -- because the user can only have one time a specific label on a star
  constraint unique_tuple unique(tag_id, celestial_bodies_id, label_id),
  -- Not sure if it is useful because these fields already are keys, so they
  -- must be indexed.
  index(userid),
  index(celestial_bodies_id)
);

create table favorites(
  id int(100) not null primary key auto_increment,
  userid int(10) not null,
  celestial_bodies_id int(10) not null,
  rank int(10) not null,
  foreign key (userid) references users(userid),
  foreign key (celestial_bodies_id) references celestial_bodies(id),
  -- A list of favorites has only 10 favorites (top 10)
  constraint checkrange check (rank between 0 and 9),
  constraint unique_rank unique(userid, rank),
  constraint unique_celestial_body unique(userid, celestial_bodies_id),
  index(userid)
);


insert into celestial_bodies (name, type) values
("Alpheratz", "star"),
("Caph", "star"),
("Eps Phe", "star"),
("Algenib", "star"),
("8Iot Cet", "star"),
("Zet Tuc", "star"),
("41 Psc", "star"),
("Bet Hyi", "star"),
("Kap Phe", "star"),
("Ankaa", "star"),
("Bet1Tuc", "star"),
("31Del And", "star"),
("Shedir", "star"),
("Diphda", "star"),
("62 Psc", "star"),
("35Nu And", "star"),
("Cih", "star"),
("37Mu And", "star"),
("Alp Scl", "star"),
("69Sig Psc", "star"),
("71Eps Psc", "star"),
("Bet Phe", "star"),
("Zet Phe", "star"),
("31Eta Cet", "star"),
("Mirach", "star"),
("85Phi Psc", "star"),
("90Ups Psc", "star"),
("45The Cet", "star"),
("Ruchbah", "star"),
("Gam Phe", "star"),
("98Mu Psc", "star"),
("Del Phe", "star"),
("99Eta Psc", "star"),
("Achernar", "star"),
("106Nu Psc", "star"),
("52Tau Cet", "star"),
("110Omi Psc", "star"),
("55Zet Cet", "star"),
("2Alp Tri", "star"),
("5Gam2Ari", "star"),
("111Xi Psc", "star"),
("Psi Phe", "star"),
("45Eps Cas", "star"),
("Sheratan", "star"),
("Chi Eri", "star"),
("Alp Hyi", "star"),
("113Alp Psc", "star"),
("Almaak", "star"),
("Hamal", "star"),
("4Bet Tri", "star"),
("65Xi 1Cet", "star"),
("Phi Eri", "star"),
("9Gam Tri", "star"),
("Mira", "star"),
("Del Hyi", "star"),
("72Rho Cet", "star"),
("Kap Eri", "star"),
("73Xi 2Cet", "star"),
("Polaris", "star"),
("76Sig Cet", "star"),
("78Nu Cet", "star"),
("82Del Cet", "star"),
("83Eps Cet", "star"),
("Eps Hyi", "star"),
("HIP 12413", "star"),
("Zet Hor", "star"),
("Iot Eri", "star"),
("86Gam Cet", "star"),
("89Pi Cet", "star"),
("87Mu Cet", "star"),
("1Tau1Eri", "star"),
("Bet For", "star"),
("41 Ari", "star"),
("16 Per", "star"),
("15Eta Per", "star"),
("3Eta Eri", "star"),
("Acamar", "star"),
("91Lam Cet", "star"),
("Menkar", "star"),
("11Tau3Eri", "star"),
("Mu Hor", "star"),
("23Gam Per", "star"),
("25Rho Per", "star"),
("Algol", "star"),
("Alp For", "star"),
("13Zet Eri", "star"),
("16Tau4Eri", "star"),
("82 G. Eri", "star"),
("Mirphak", "star"),
("1Omi Tau", "star"),
("HIP 16228", "star"),
("18Eps Eri", "star"),
("19Tau5Eri", "star"),
("39Del Per", "star"),
("23Del Eri", "star"),
("Bet Ret", "star"),
("38Omi Per", "star"),
("27Tau6Eri", "star"),
("Gam Hyi", "star"),
("HIP 17797", "star"),
("27 Tau", "star"),
("HIP 17874", "star"),
("Gam Cam", "star"),
("44Zet Per", "star"),
("HIP 18505", "star"),
("45Eps Per", "star"),
("Del Ret", "star"),
("46Xi Per", "star"),
("35Lam Tau", "star"),
("Alp Hor", "star"),
("Alp Ret", "star"),
("Gam Dor", "star"),
("Eps Ret", "star"),
("41Ups4Eri", "star"),
("54Gam Tau", "star"),
("61Del1Tau", "star"),
("43 Eri", "star"),
("68Del3Tau", "star"),
("74Eps Tau", "star"),
("78The2Tau", "star"),
("Del Cae", "star"),
("Alp Dor", "star"),
("52Ups2Eri", "star"),
("Aldebaran", "star"),
("48Nu Eri", "star"),
("53 Eri", "star"),
("Alp Cae", "star"),
("Bet Cae", "star"),
("94Tau Tau", "star"),
("Mu Men", "star"),
("57Mu Eri", "star"),
("1Pi 3Ori", "star"),
("2Pi 2Ori", "star"),
("3Pi 4Ori", "star"),
("61Ome Eri", "star"),
("5 Ori", "star"),
("9Alp Cam", "star"),
("7Pi 1Ori", "star"),
("Hassaleh", "star"),
("10Pi 6Ori", "star"),
("8Zet Aur", "star"),
("2Eps Lep", "star"),
("Cursa", "star"),
("69Lam Eri", "star"),
("3Iot Lep", "star"),
("5Mu Lep", "star"),
("4Kap Lep", "star"),
("Rigel", "star"),
("Capella", "star"),
("6Lam Lep", "star"),
("7Nu Lep", "star"),
("Gl 196", "star"),
("Bellatrix", "star"),
("Alnath", "star"),
("Nihal", "star"),
("Eps Col", "star"),
("Gam Men", "star"),
("Mintaka", "star"),
("Arneb", "star"),
("Bet Dor", "star"),
("39Lam Ori", "star"),
("Alnilam", "star"),
("123Zet Tau", "star"),
("Phakt", "star"),
("Alnitak", "star"),
("13Gam Lep", "star"),
("Del Dor", "star"),
("14Zet Lep", "star"),
("Bet Pic", "star"),
("Saiph", "star"),
("Gam Pic", "star"),
("Bet Col", "star"),
("15Del Lep", "star"),
("Gl 224.1", "star"),
("54Chi1Ori", "star"),
("Betelgeuse", "star"),
("16Eta Lep", "star"),
("Gam Col", "star"),
("Eta Col", "star"),
("Menkalinan", "star"),
("37The Aur", "star"),
("61Mu Ori", "star"),
("64 Ori", "star"),
("1 Gem", "star"),
("18The Lep", "star"),
("67Nu Ori", "star"),
("HIP 29151", "star"),
("70Xi Ori", "star"),
("5Gam Mon", "star"),
("7Eta Gem", "star"),
("Kap Col", "star"),
("2 Lyn", "star"),
("1Zet CMa", "star"),
("Del Col", "star"),
("Mirzam", "star"),
("13Mu Gem", "star"),
("8Eps Mon", "star"),
("Canopus", "star"),
("11Bet Mon", "star"),
("18Nu Gem", "star"),
("5Xi 2CMa", "star"),
("7Nu 2CMa", "star"),
("Alhena", "star"),
("Nu Pup", "star"),
("27Eps Gem", "star"),
("Sirius", "star"),
("31Xi Gem", "star"),
("Alp Pic", "star"),
("13Kap CMa", "star"),
("Tau Pup", "star"),
("34The Gem", "star"),
("14The CMa", "star"),
("HIP 33165", "star"),
("20Iot CMa", "star"),
("15 Lyn", "star"),
("Adhara", "star"),
("22Sig CMa", "star"),
("24Omi2CMa", "star"),
("23Gam CMa", "star"),
("43Zet Gem", "star"),
("Wezen", "star"),
("Gam2Vol", "star"),
("46Tau Gem", "star"),
("22Del Mon", "star"),
("28Ome CMa", "star"),
("Del Vol", "star"),
("Pi Pup", "star"),
("54Lam Gem", "star"),
("55Del Gem", "star"),
("Aludra", "star"),
("60Iot Gem", "star"),
("21 Lyn", "star"),
("Gomeisa", "star"),
("Sig Pup", "star"),
("Castor", "star"),
("69Ups Gem", "star"),
("Procyon", "star"),
("26Alp Mon", "star"),
("Zet Vol", "star"),
("77Kap Gem", "star"),
("Pollux", "star"),
("HIP 38146", "star"),
("Naos", "star"),
("15Rho Pup", "star"),
("Eps Vol", "star"),
("29Zet Mon", "star"),
("Gam2Vel", "star"),
("17Bet Cnc", "star"),
("Alp Cha", "star"),
("18Chi Cnc", "star"),
("Avior", "star"),
("31 Lyn", "star"),
("Bet Vol", "star"),
("1Omi UMa", "star"),
("4Del Hya", "star"),
("5Sig Hya", "star"),
("Bet Pyx", "star"),
("HIP 42536", "star"),
("HIP 42568", "star"),
("7Eta Hya", "star"),
("43Gam Cnc", "star"),
("Alp Pyx", "star"),
("47Del Cnc", "star"),
("Del Vel", "star"),
("48Iot Cnc", "star"),
("11Eps Hya", "star"),
("13Rho Hya", "star"),
("Gam Pyx", "star"),
("16Zet Hya", "star"),
("65Alp Cnc", "star"),
("9Iot UMa", "star"),
("Gl 332A", "star"),
("Alp Vol", "star"),
("12Kap UMa", "star"),
("HIP 44700", "star"),
("Lam Vel", "star"),
("HIP 45080", "star"),
("Miaplacidus", "star"),
("22The Hya", "star"),
("Tureis", "star"),
("38 Lyn", "star"),
("40Alp Lyn", "star"),
("Kap Vel", "star"),
("Alphard", "star"),
("31Tau1Hya", "star"),
("Psi Vel", "star"),
("23 UMa", "star"),
("32Tau2Hya", "star"),
("25The UMa", "star"),
("10 LMi", "star"),
("Ras Elased Australis", "star"),
("29Ups UMa", "star"),
("39Ups1Hya", "star"),
("30Phi UMa", "star"),
("24Mu Leo", "star"),
("Phi Vel", "star"),
("Eta Ant", "star"),
("30Eta Leo", "star"),
("21 LMi", "star"),
("15Alp Sex", "star"),
("Regulus", "star"),
("41Lam Hya", "star"),
("Ome Car", "star"),
("HIP 50191", "star"),
("36Zet Leo", "star"),
("HIP 50371", "star"),
("33Lam UMa", "star"),
("Algieba", "star"),
("34Mu UMa", "star"),
("42Mu Hya", "star"),
("Alp Ant", "star"),
("HIP 51232", "star"),
("31Bet LMi", "star"),
("30Bet Sex", "star"),
("Gam Cha", "star"),
("HIP 51986", "star"),
("The Car", "star"),
("HIP 52468", "star"),
("Mu Vel", "star"),
("Nu Hya", "star"),
("46 LMi", "star"),
("Gl 404.1", "star"),
("7Alp Crt", "star"),
("Merak", "star"),
("Dubhe", "star"),
("HIP 54463", "star"),
("52Psi UMa", "star"),
("11Bet Crt", "star"),
("Zosma", "star"),
("70The Leo", "star"),
("12Del Crt", "star"),
("14Eps Crt", "star"),
("15Gam Crt", "star"),
("1Lam Dra", "star"),
("Xi Hya", "star"),
("HIP 56480", "star"),
("Lam Cen", "star"),
("21The Crt", "star"),
("27Zet Crt", "star"),
("Lam Mus", "star"),
("3Nu Vir", "star"),
("63Chi UMa", "star"),
("Denebola", "star"),
("Bet Hya", "star"),
("Phad", "star"),
("30Eta Crt", "star"),
("Del Cen", "star"),
("1Alp Crv", "star"),
("2Eps Crv", "star"),
("Del Cru", "star"),
("Megrez", "star"),
("Gienah Ghurab", "star"),
("Bet Cha", "star"),
("13 Vir", "star"),
("Acrux", "star"),
("15Gam Com", "star"),
("Sig Cen", "star"),
("Algorab", "star"),
("Gacrux", "star"),
("8Eta Crv", "star"),
("Gam Mus", "star"),
("5Kap Dra", "star"),
("8Bet CVn", "star"),
("Kraz", "star"),
("Alp Mus", "star"),
("Gam Cen", "star"),
("Porrima", "star"),
("Bet Mus", "star"),
("Becrux", "star"),
("Alioth", "star"),
("43Del Vir", "star"),
("Cor Caroli", "star"),
("Vindemiatrix", "star"),
("45Psi Hya", "star"),
("42Alp Com", "star"),
("43Bet Com", "star"),
("46Gam Hya", "star"),
("Iot Cen", "star"),
("Mizar", "star"),
("Spica", "star"),
("HIP 65936", "star"),
("79Zet Vir", "star"),
("Eps Cen", "star"),
("Alkaid", "star"),
("5Ups Boo", "star"),
("Nu Cen", "star"),
("Mu Cen", "star"),
("Mufrid", "star"),
("Zet Cen", "star"),
("Ups1Cen", "star"),
("93Tau Vir", "star"),
("Hadar", "star"),
("Thuban", "star"),
("Menkent", "star"),
("98Kap Vir", "star"),
("Arcturus", "star"),
("99Iot Vir", "star"),
("Tau2Lup", "star"),
("Del Oct", "star"),
("25Rho Boo", "star"),
("27Gam Boo", "star"),
("Eta Cen", "star"),
("Rho Lup", "star"),
("Rigil Kentaurus", "star"),
("30Zet Boo", "star"),
("Alp Lup", "star"),
("Alp Cir", "star"),
("107Mu Vir", "star"),
("Izar", "star"),
("109 Vir", "star"),
("Alp Aps", "star"),
("Kochab", "star"),
("Zubenelgenubi", "star"),
("Bet Lup", "star"),
("Kap Cen", "star"),
("42Bet Boo", "star"),
("20Sig Lib", "star"),
("Zet Lup", "star"),
("49Del Boo", "star"),
("Zubeneschemali", "star"),
("Bet Cir", "star"),
("Gam TrA", "star"),
("13Gam UMi", "star"),
("Del Lup", "star"),
("Phi1Lup", "star"),
("Gam Cir", "star"),
("12Iot Dra", "star"),
("3Bet CrB", "star"),
("4The CrB", "star"),
("Alphekka", "star"),
("13Del Ser", "star"),
("Gam Lup", "star"),
("38Gam Lib", "star"),
("Ome Lup", "star"),
("8Gam CrB", "star"),
("16Zet UMi", "star"),
("Unukalhai", "star"),
("28Bet Ser", "star"),
("35Kap Ser", "star"),
("10Del CrB", "star"),
("32Mu Ser", "star"),
("37Eps Ser", "star"),
("5Chi Lup", "star"),
("1Chi Her", "star"),
("46The Lib", "star"),
("Bet TrA", "star"),
("41Gam Ser", "star"),
("13Eps CrB", "star"),
("6Pi Sco", "star"),
("Eta Lup", "star"),
("Dschubba", "star"),
("14Iot CrB", "star"),
("13The Dra", "star"),
("Eta Nor", "star"),
("Graffias", "star"),
("HIP 78970", "star"),
("Kap Nor", "star"),
("21Eta UMi", "star"),
("2Eps Oph", "star"),
("22Tau Her", "star"),
("Gam2Nor", "star"),
("20Gam Her", "star"),
("14Eta Dra", "star"),
("Eps Nor", "star"),
("Antares", "star"),
("Kornephoros", "star"),
("Gam Aps", "star"),
("35Sig Her", "star"),
("23Tau Sco", "star"),
("13Zet Oph", "star"),
("40Zet Her", "star"),
("44Eta Her", "star"),
("Bet Aps", "star"),
("22Eps UMi", "star"),
("Atria", "star"),
("Eta Ara", "star"),
("26Eps Sco", "star"),
("Mu 1Sco", "star"),
("Zet1Sco", "star"),
("27Kap Oph", "star"),
("Zet Ara", "star"),
("58Eps Her", "star"),
("22Zet Dra", "star"),
("35Eta Oph", "star"),
("Eta Sco", "star"),
("65Del Her", "star"),
("67Pi Her", "star"),
("69 Her", "star"),
("53Nu Ser", "star"),
("75Rho Her", "star"),
("Bet Ara", "star"),
("Gam Ara", "star"),
("Rastaban", "star"),
("76Lam Her", "star"),
("Del Ara", "star"),
("51 Oph", "star"),
("Alp Ara", "star"),
("23Del UMi", "star"),
("25Nu 2Dra", "star"),
("Shaula", "star"),
("Rasalhague", "star"),
("Sargas", "star"),
("55Xi Ser", "star"),
("85Iot Her", "star"),
("56Omi Ser", "star"),
("Kap Sco", "star"),
("Cebalrai", "star"),
("Eta Pav", "star"),
("86Mu Her", "star"),
("3 Sgr", "star"),
("Iot1Sco", "star"),
("32Xi Dra", "star"),
("91The Her", "star"),
("Etamin", "star"),
("92Xi Her", "star"),
("Nash", "star"),
("The Ara", "star"),
("103Omi Her", "star"),
("Pi Pav", "star"),
("13Mu Sgr", "star"),
("Eta Sgr", "star"),
("Kaus Meridionalis", "star"),
("44Chi Dra", "star"),
("58Eta Ser", "star"),
("Xi Pav", "star"),
("Kaus Australis", "star"),
("Alp Tel", "star"),
("Kaus Borealis", "star"),
("Zet Tel", "star"),
("Gam Sct", "star"),
("HIP 90887", "star"),
("Alp Sct", "star"),
("Vega", "star"),
("Zet Pav", "star"),
("Lam CrA", "star"),
("6Zet1Lyr", "star"),
("27Phi Sgr", "star"),
("Bet Sct", "star"),
("HIP 92202", "star"),
("Sheliak", "star"),
("Lam Pav", "star"),
("12Del2Lyr", "star"),
("HIP 92814", "star"),
("Nunki", "star"),
("63The1Ser", "star"),
("HIP 92953", "star"),
("HIP 92989", "star"),
("Kap Pav", "star"),
("37Xi 2Sgr", "star"),
("Eps CrA", "star"),
("14Gam Lyr", "star"),
("13Eps Aql", "star"),
("38Zet Sgr", "star"),
("Zet CrA", "star"),
("39Omi Sgr", "star"),
("17Zet Aql", "star"),
("16Lam Aql", "star"),
("Gam CrA", "star"),
("40Tau Sgr", "star"),
("Del CrA", "star"),
("Alp CrA", "star"),
("Bet CrA", "star"),
("57Del Dra", "star"),
("60Tau Dra", "star"),
("1Kap Cyg", "star"),
("43 Sgr", "star"),
("44Rho1Sgr", "star"),
("Bet2Sgr", "star"),
("Alp Sgr", "star"),
("30Del Aql", "star"),
("6Alp Vul", "star"),
("10Iot2Cyg", "star"),
("Albireo", "star"),
("51 Sgr", "star"),
("5Alp Sge", "star"),
("6Bet Sge", "star"),
("18Del Cyg", "star"),
("Tarazed", "star"),
("7Del Sge", "star"),
("63Eps Dra", "star"),
("Altair", "star"),
("55Eta Aql", "star"),
("Iot Sgr", "star"),
("Alshain", "star"),
("21Eta Cyg", "star"),
("12Gam Sge", "star"),
("The1Sgr", "star"),
("Eps Pav", "star"),
("15 Vul", "star"),
("62 Sgr", "star"),
("16Eta Sge", "star"),
("Del Pav", "star"),
("65The Aql", "star"),
("6Alp2Cap", "star"),
("9Bet Cap", "star"),
("Sadr", "star"),
("Peacock", "star"),
("2Eps Del", "star"),
("6Bet Del", "star"),
("Alp Ind", "star"),
("9Alp Del", "star"),
("Deneb", "star"),
("11Del Del", "star"),
("Bet Pav", "star"),
("16Psi Cap", "star"),
("Gienah", "star"),
("12Gam2Del", "star"),
("2Eps Aqr", "star"),
("Alp Mic", "star"),
("18Ome Cap", "star"),
("Bet Ind", "star"),
("Gam Mic", "star"),
("23The Cap", "star"),
("5Gam Equ", "star"),
("64Zet Cyg", "star"),
("7Del Equ", "star"),
("8Alp Equ", "star"),
("Eps Mic", "star"),
("Alderamin", "star"),
("The Ind", "star"),
("32Iot Cap", "star"),
("10Bet Equ", "star"),
("Gam Pav", "star"),
("34Zet Cap", "star"),
("8Bet Cep", "star"),
("Sadalsuud", "star"),
("40Gam Cap", "star"),
("Nu Oct", "star"),
("78Mu 1Cyg", "star"),
("Enif", "star"),
("10Kap Peg", "star"),
("49Del Cap", "star"),
("10The PsA", "star"),
("Gam Gru", "star"),
("12Eta PsA", "star"),
("Sadalmelik", "star"),
("Lam Gru", "star"),
("33Iot Aqr", "star"),
("24Iot Peg", "star"),
("Alnair", "star"),
("27Pi 1Peg", "star"),
("15Tau PsA", "star"),
("26The Peg", "star"),
("21Zet Cep", "star"),
("1 Lac", "star"),
("43The Aqr", "star"),
("Alp Tuc", "star"),
("48Gam Aqr", "star"),
("3Bet Lac", "star"),
("4 Lac", "star"),
("55Zet1Aqr", "star"),
("Del1Gru", "star"),
("5 Lac", "star"),
("6 Lac", "star"),
("57Sig Aqr", "star"),
("7Alp Lac", "star"),
("17Bet PsA", "star"),
("62Eta Aqr", "star"),
("18Eps PsA", "star"),
("42Zet Peg", "star"),
("Bet Gru", "star"),
("Matar", "star"),
("Bet Oct", "star"),
("47Lam Peg", "star"),
("46Xi Peg", "star"),
("Eps Gru", "star"),
("71Tau2Aqr", "star"),
("32Iot Cep", "star"),
("48Mu Peg", "star"),
("73Lam Aqr", "star"),
("76Del Aqr", "star"),
("23Del PsA", "star"),
("Fomalhaut", "star"),
("Zet Gru", "star"),
("Scheat", "star"),
("Markab", "star"),
("The Gru", "star"),
("88 Aqr", "star"),
("Iot Gru", "star"),
("91Psi1Aqr", "star"),
("6Gam Psc", "star"),
("Gam Tuc", "star"),
("Gam Scl", "star"),
("98 Aqr", "star"),
("8Kap Psc", "star"),
("10The Psc", "star"),
("Bet Scl", "star"),
("35Gam Cep", "star"),
("17Iot Psc", "star"),
("18Lam Psc", "star"),
("28Ome Psc", "star"),
("Aquila", "constellation"),
("Andromeda", "constellation"),
("Sculptor", "constellation"),
("Ara", "constellation"),
("Libra", "constellation"),
("Cetus", "constellation"),
("Aries", "constellation"),
("Scutum", "constellation"),
("Pyxis", "constellation"),
("Bootes", "constellation"),
("Caelum", "constellation"),
("Chamaeleon", "constellation"),
("Cancer", "constellation"),
("Capricornus", "constellation"),
("Carina", "constellation"),
("Cassiopeia", "constellation"),
("Centaurus", "constellation"),
("Cepheus", "constellation"),
("Coma Berenices", "constellation"),
("Canes Venatici", "constellation"),
("Auriga", "constellation"),
("Columba", "constellation"),
("Circinus", "constellation"),
("Crater", "constellation"),
("Corona Australis", "constellation"),
("Corona Borealis", "constellation"),
("Corvus", "constellation"),
("Crux", "constellation"),
("Cygnus", "constellation"),
("Delphinus", "constellation"),
("Dorado", "constellation"),
("Draco", "constellation"),
("Norma", "constellation"),
("Eridanus", "constellation"),
("Sagitta", "constellation"),
("Fornax", "constellation"),
("Gemini", "constellation"),
("Camelopardalis", "constellation"),
("Canis Major", "constellation"),
("Ursa Major", "constellation"),
("Grus", "constellation"),
("Hercules", "constellation"),
("Horologium", "constellation"),
("Hydra", "constellation"),
("Hydrus", "constellation"),
("Indus", "constellation"),
("Lacerta", "constellation"),
("Monoceros", "constellation"),
("Lepus", "constellation"),
("Leo", "constellation"),
("Lupus", "constellation"),
("Lynx", "constellation"),
("Lyra", "constellation"),
("Antlia", "constellation"),
("Microscopium", "constellation"),
("Musca", "constellation"),
("Octans", "constellation"),
("Apus", "constellation"),
("Ophiuchus", "constellation"),
("Orion", "constellation"),
("Pavo", "constellation"),
("Pegasus", "constellation"),
("Pictor", "constellation"),
("Perseus", "constellation"),
("Equuleus", "constellation"),
("Canis Minor", "constellation"),
("Leo Minor", "constellation"),
("Vulpecula", "constellation"),
("Ursa Minor", "constellation"),
("Phoenix", "constellation"),
("Pisces", "constellation"),
("Piscis Austrinus", "constellation"),
("Volans", "constellation"),
("Puppis", "constellation"),
("Reticulum", "constellation"),
("Sagittarius", "constellation"),
("Scorpius", "constellation"),
("Serpens", "constellation"),
("Sextans", "constellation"),
("Mensa", "constellation"),
("Taurus", "constellation"),
("Telescopium", "constellation"),
("Tucana", "constellation"),
("Triangulum", "constellation"),
("Triangulum Australe", "constellation"),
("Aquarius", "constellation"),
("Virgo", "constellation"),
("Vela", "constellation"),
("Soleil", "planet"),
("Mercure", "planet"),
("Venus", "planet"),
("Terre", "planet"),
("Lune", "moon"),
("Mars", "planet"),
("Phobos", "moon"),
("Deimos", "moon"),
("Jupiter", "planet"),
("Io", "moon"),
("Europe", "moon"),
("Ganymede", "moon"),
("Callisto", "moon"),
("Saturne", "planet"),
("Mimas", "moon"),
("Encelade", "moon"),
("Tethys", "moon"),
("Dione", "moon"),
("Rhea", "moon"),
("Titan", "moon"),
("Hyperion", "moon"),
("Japet", "moon"),
("Uranus", "planet"),
("Ariel", "moon"),
("Umbriel", "moon"),
("Titania", "moon"),
("Oberon", "moon"),
("Miranda", "moon"),
("Neptune", "planet"),
("Triton", "moon");

